version: '3'
services:
  db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./data:/var/lib/postgresql/data

  api:
    command: go run .
    working_dir: /go/src/uow
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./sql:/go/src/uow/sql
      - ./uow:/go/src/uow/uow
      - ./user:/go/src/uow/user
      - ./bootstrap.go:/go/src/uow/bootstrap.go
      - ./main.go:/go/src/uow/main.go
